services:
  mmodel-server:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    command: ["--addr", ":8080", "--data", "/data", "--graphstore", "file.memory"]
    ports:
      - "8080:8080"
    volumes:
      - mmodel-data:/data

volumes:
  mmodel-data: {}
